### Python Data Structures
##### list
##### Dictionary
##### Tuple
##### Set

### Lists

In [1]:
my_list = [1,2,3,4,5]

In [2]:
print(my_list)

[1, 2, 3, 4, 5]


In [3]:
my_list = [1,2,3,'abc',3.123,23432847234]

In [4]:
print(my_list)

[1, 2, 3, 'abc', 3.123, 23432847234]


In [5]:
my_list = [1,2,3,4,5]
my_list.append([6,7])
print(my_list)

[1, 2, 3, 4, 5, [6, 7]]


In [6]:
my_list = [1,2,3,4,5]
my_list.extend([6,7])
print(my_list)

[1, 2, 3, 4, 5, 6, 7]


In [9]:
my_list2 = [32,45,67,89,12]
my_list2.insert(1,234324)

In [10]:
print(my_list2)

[32, 234324, 45, 67, 89, 12]


In [11]:
my_list2.remove(234324)

In [12]:
print(my_list2)

[32, 45, 67, 89, 12]


In [14]:
my_list = [12,14,16,18,20,22]

In [17]:
my_list[2:5]

[16, 18, 20]

### slicing

my_list[start : end+1 : step]

In [24]:
my_list[::-1]

[22, 20, 18, 16, 14, 12]

In [25]:
len(my_list)

6

In [26]:
my_list.index(16)

2

In [28]:
my_list = [33,2,12,45,5]
x = sorted(my_list)

[2, 5, 12, 33, 45]

In [29]:
my_list.sort()

In [30]:
my_list

[2, 5, 12, 33, 45]

### Dictionary

In [31]:
my_dict = {'Tehran':32, 'Yazd':25, 'Arak':15}

In [32]:
my_dict['Tehran']

32

In [35]:
list(my_dict.keys())

['Tehran', 'Yazd', 'Arak']

In [37]:
list(my_dict.values())

[32, 25, 15]

In [38]:
list(my_dict.items())

[('Tehran', 32), ('Yazd', 25), ('Arak', 15)]

### Tuple

In [39]:
my_tuple = (1,2,3)

In [40]:
print(my_tuple)

(1, 2, 3)


In [43]:
print(my_list)

[2, 5, 50, 33, 45]


In [42]:
my_list[2] = 50

In [44]:
my_tuple[1] = 50

TypeError: 'tuple' object does not support item assignment

In [45]:
my_tuple = my_tuple + (4,5,6)

In [46]:
print(my_tuple)

(1, 2, 3, 4, 5, 6)


### Sets

In [47]:
my_set = {1,2,3,4,5,5,5}

In [48]:
print(my_set)

{1, 2, 3, 4, 5}


In [49]:
my_set.add(0)

In [50]:
print(my_set)

{0, 1, 2, 3, 4, 5}


In [52]:
my_set1 = {1,2,3,4}
my_set2 = {3,4,5,6}

In [53]:
my_set1.union(my_set2)

{1, 2, 3, 4, 5, 6}

In [54]:
my_set1.intersection(my_set2)

{3, 4}

In [55]:
my_set1.difference(my_set2)

{1, 2}

### Loops, Logics, and Functions

In [57]:
list(range(2,20,3))

[2, 5, 8, 11, 14, 17]

In [58]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [62]:
for i in range(10):
    print("the number is ",i)

the number is  0
the number is  1
the number is  2
the number is  3
the number is  4
the number is  5
the number is  6
the number is  7
the number is  8
the number is  9


In [63]:
num = -3.4

In [65]:
if num > 0:
    print("positive number")
elif num == 0:
    print("zero")
else:
    print("negative number")

negative number


In [66]:
city_demand = {'tehran':90, 'esfahan':55, 'kerman':77}

In [68]:
# user input
city_name = 'tehran'

# evaluate
for c in city_demand:
    if city_name == c:
        print("demand of ",c," is ",city_demand[c])
        break

demand of  tehran  is  90


In [69]:
def demand_fun(city_name):
    for c in city_demand:
        if city_name == c:
            break
    return city_demand[c]

In [71]:
demand_fun('tehran')

90

### how to import libraries?

In [75]:
from math import pi,sqrt

In [77]:
import math as mp

In [78]:
mp.pi

3.141592653589793

In [79]:
from math import sqrt as sq

In [80]:
sq(3)

1.7320508075688772

### NUMPY

In [81]:
import numpy as np

In [82]:
my_list = [1,2,3,4]

In [83]:
my_array = np.array(my_list)

In [84]:
print(my_array)

[1 2 3 4]


In [85]:
print(my_list)

[1, 2, 3, 4]


In [86]:
print(type(my_list))

<class 'list'>


In [87]:
print(type(my_array))

<class 'numpy.ndarray'>


In [88]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

In [89]:
my_2d_list = [list1,list2,list3]

In [91]:
print(my_2d_list)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [92]:
my_2d_array = np.array([list1,list2,list3])

In [93]:
print(my_2d_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
my_2d_array.dtype

dtype('int32')

In [96]:
my_array_2 = np.array([0,0.2,4])

In [97]:
my_array_2.dtype

dtype('float64')

In [102]:
x = np.arange(1,13).reshape((3,4))

In [103]:
print(x.ndim)

2


In [104]:
print(x.size)

12


In [107]:
x.shape[1]

4

In [112]:
y = np.arange(15,27)

In [109]:
print(y)

[15 16 17 18 19 20 21 22 23 24 25]


In [110]:
y[4:7]

array([19, 20, 21])

In [113]:
z = y.reshape((3,4))

In [114]:
print(z)

[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]


In [115]:
z[:,0]

array([15, 19, 23])

z[a:b:step1,q:w:step2]

In [116]:
np.transpose(z)

array([[15, 19, 23],
       [16, 20, 24],
       [17, 21, 25],
       [18, 22, 26]])

In [117]:
z.T

array([[15, 19, 23],
       [16, 20, 24],
       [17, 21, 25],
       [18, 22, 26]])

In [118]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.ones((5,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [121]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [122]:
np.arange(2,3,.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [124]:
np.linspace(2,3,num=5,endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [125]:
np.random.rand(3,2)

array([[0.23092674, 0.33626233],
       [0.78738569, 0.09735869],
       [0.91723643, 0.28646693]])

In [126]:
np.random.randint(10,20,(3,2))

array([[16, 19],
       [16, 10],
       [11, 17]])